### ISSUE TITLE
Save As Text/XML

### ISSUE THREAD

**Issue by perlmunger** [patsplat/plist#24]
Is there any way to tell the library to save as text/xml instead of binary?

**Comment by mattbrictson** [comment]
Not sure what you mean... As the [examples in the README](https://github.com/patsplat/plist#creating-a-plist) show, the library generates XML, not binary.

I'm closing since this issue is nearly 2 years old and I'm sure you've moved on. If you'd like to continue the discussion, let me know and I'll reopen the issue.
